Added support for @QueryParam annotation
misternerd/resteasytox-maven-plugin pull request #2
Opened 2017-09-11 22:35 UTC by SergeKorobko

Hi, 

I've made some little changes in your plugin - not it knows how to deal with jax-rs @QueryParam annotation.

It would be great to have this feature in master. 

Thanks.

2017-09-27 18:20 UTC, misternerd commented
@SergeKorobko Sorry for the delay, I was on vacation. I'll try to review your PR over the weekend.

2017-10-07 21:19 UTC, misternerd requested changes
Hey Serge, I added a few comments to your PR. It would be great if you can fix them or write me feedback on them. Thanks!

2017-10-07 21:19 UTC, misternerd commented on src/main/java/com/misternerd/resteasytox/RestServiceLayout.java
> +					logger.debug("Query parameter will be discarded for method=" + method.getName());
@SergeKorobko Please remove the logger here, looks like it is left over

2017-10-07 21:19 UTC, misternerd commented on src/main/java/com/misternerd/resteasytox/javascript/ResteasyToJavascriptConverter.java
> +			if(!serviceMethod.queryParams.isEmpty()) {
@SergeKorobko I think it makes sense to support query params for all types of request. Please move this URL generating block up and use it for all method types.

2017-10-19 21:00 UTC, SergeKorobko reviewed
Hi, @misternerd. Did you had a chance to take a look on merge request?

2017-10-19 21:00 UTC, SergeKorobko commented on src/main/java/com/misternerd/resteasytox/javascript/ResteasyToJavascriptConverter.java
> +			if(!serviceMethod.queryParams.isEmpty()) {
@misternerd : done.

2017-10-24 08:06 UTC, merged

2017-10-24 08:06 UTC, misternerd commented
Hi @SergeKorobko, finally got around to do this, thanks for your patience!

2017-10-24 08:17 UTC, SergeKorobko commented
Hi @misternerd, thank you!